### ISSUE TITLE
 The player can fly outside the island boundaries.

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/IslandFly#23]
#### Screenshots and videos
https://streamable.com/0pgb7

#### Server
 - OS: **CentOS 7**
 - Java version: **8**

#### Plugins

![image](https://user-images.githubusercontent.com/47111280/68084025-1d55c380-fe41-11e9-8a75-6bbea8c1c657.png)

##### BentoBox and Addons
![image](https://user-images.githubusercontent.com/47111280/68084029-29418580-fe41-11e9-90e1-326bb9fea611.png)

####Extra:
Players cannot fly on the nether and end islands. Each time "Flying mode is turned on." says.

**Comment by tastybento** [comment]
I can't replicate this right now - it all seems to work.

Players who are Op or who have `bskyblock.island.flybypass` permission can fly outside the border. Maybe this player has this permission or a * permission of some kind?

**Comment by OverBrave** [comment]
No. 
Players do not have these privileges.

**Comment by tastybento** [comment]
I need more info - 

1. Is the player a member of the island?
2. Is it the owner or team member?
3. What messages does the player see when they fly outside of the boundary? Please list all of them. 
4. What is the output of ‘/bsb info’ on the island and the output of ‘/bsb info playerName’

I may have to give you a debut build of the addon. Okay? It would probably be easiest.

**Comment by OverBrave** [comment]
1. Yes
2. Member
3. Only said "You left the island." notification is coming.
4. 
![image](https://user-images.githubusercontent.com/47111280/68210623-f33e0600-ffe6-11e9-929e-3bc3974cb5a3.png)


Ok.

**Comment by Poslovitch** [comment]
We would need that output in English though.

**Comment by tastybento** [comment]
I'll prepare a debug build that will tell us what is going on.

**Comment by tastybento** [comment]
[IslandFly-1.7.0-SNAPSHOT-LOCAL.jar.zip](https://github.com/BentoBoxWorld/IslandFly/files/3810379/IslandFly-1.7.0-SNAPSHOT-LOCAL.jar.zip)
Please try this and share the **console** log. Have the player exit the island like in the video and then share the log that results. Thanks!

**Comment by OverBrave** [comment]
![image](https://user-images.githubusercontent.com/47111280/68232778-e3d2b300-000e-11ea-99b8-5e5f0dd363a7.png)

**Comment by tastybento** [comment]
Thanks. Please try this version:
[IslandFly-1.7.0-SNAPSHOT-LOCAL.jar.zip](https://github.com/BentoBoxWorld/IslandFly/files/3811792/IslandFly-1.7.0-SNAPSHOT-LOCAL.jar.zip)

**Comment by OverBrave** [comment]
![image](https://user-images.githubusercontent.com/47111280/68295973-97d24d80-00a4-11ea-8af2-e59a96d4cf30.png)
![image](https://user-images.githubusercontent.com/47111280/68295985-9e60c500-00a4-11ea-8f06-a26a8a4bbe04.png)
Another error message

**Comment by BONNe** [comment]
Does not relate to fly addon!
Please create a separate issue in BentoBox repository.

**Comment by tastybento** [comment]
Ignore the error message - that is fixed in latest bentoBox build and unrelated.

In regards to the fly debug, let me check the sequence of events to confirm:

1. You give xEnder permission to fly
2. xEnder then exits the island boundary (jumps off the island and gets the leaving island message)
3. xEnder then issues the `/island fly` command and is then able to fly outside the boundary
4. xEnder then returns to the island

Question: it looks like your islands go right next to each other - correct? What is the island distance and island protection sizes?

(BTW, in future, please copy and paste text instead of screenshot - thanks!)

**Comment by tastybento** [comment]
BTW, if the above is true,  then I expect the player is jumping over the island boundary check and then typing fly. IslandFly checks boundaries only when the player exits the island boundary and does not check continuously.

**Comment by OverBrave** [comment]
No.
BSkyblock Config.;
`  distance-between-islands: 75
  protection-range: 15`

**Comment by tastybento** [comment]
Is this sequence correct though:

You give xEnder permission to fly
Ender then exits the island boundary
Ender then issues the /island fly command and is then able to fly outside the boundary
Ender then returns to the island

**Comment by OverBrave** [comment]
Yes.

**Comment by tastybento** [comment]
Should be fixed now.

**Comment by OverBrave** [comment]
There's a problem. Can you check that out?
Red text warns that it will close. The purple text indicates that the flying mode is back on.
https://streamable.com/ycbs1

**Comment by wellnesscookie** [comment]
This is happening because `IslandEvent.IslandExitEvent` is triggered when leaving the range that is already set for your island, but if the distance between islands is not as same as range:
`Island is = addon.getIslands().getIslandAt(user.getLocation()).orElse(null);` will still return the closest island, while it should return null (if user is beyond protection range). 

I see no API that only checks if user is within a protection range of **any** island, and not only his own.   `public boolean userIsOnIsland(World world, User user)` will only check for user's own island, but not for others as well. The problem now is that the IslandFly supports using fly command on other islands too.

**Comment by OverBrave** [comment]
But he can fly to another island and fly mode does not turn off. Anyway, when he enters another island, can you turn off the flight mode if the island doesn't belong to him?

**Comment by wellnesscookie** [comment]
The problem was of other nature. I opened a pull request that fixes it.
Found the part of API I needed!

**Comment by OverBrave** [comment]
The latest update also is effective on op. #95 dev build

**Comment by tastybento** [comment]
Okay, so I should ignore Ops.

**Comment by tastybento** [comment]
Should be fixed now with latest build.
